sudo: required

language: python

services:
  - docker

cache:
  directories:
    - .cache/pip

matrix:
  include:
    - env: TARGET_XXXXXX=linux-x32
    - env: TARGET_XXXXXX=linux-x64

script:
  - "bash build-${TARGET_XXXXXX}.sh"
