sudo: required

language: python

services:
  - docker

# cache:
#   directories:
#     - .cache/pip

matrix:
  include:
    - env: TARGET=linux-x32
    - env: TARGET=linux-x64

script:
- "bash build-${TARGET}.sh"
